import { ModalContextProvier } from "@/components/modal/context/ModalContextProvider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Modal from "@/components/modal/Modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex justify-center items-center`}>
        <ModalContextProvier>{children}</ModalContextProvier>
      </body>
    </html>
  );
}
